vim.keymap.set({ 'n' }, 'gh', '0')
vim.keymap.set({ 'n' }, 'gs', '^')
vim.keymap.set({ 'n' }, 'gl', '$')

vim.keymap.set({ 'n' }, 'gK', vim.lsp.buf.signature_help, { buffer = true, desc = 'Signature help' })
vim.keymap.set({ 'n' }, '<leader>ca', vim.lsp.buf.code_action, { buffer = true, desc = 'Code action' })
vim.keymap.set({ 'n' }, '<leader>cc', vim.lsp.codelens.run, { buffer = true, desc = 'Code lens' })
vim.keymap.set({ 'n' }, '<leader>cC', vim.lsp.codelens.refresh, { buffer = true, desc = 'Code lens refresh' })
vim.keymap.set({ 'n' }, '<leader>cr', vim.lsp.buf.rename, { buffer = true, desc = 'Rename' })
vim.keymap.set({ 'n' }, '<leader>cR', function()
    require('snacks').rename.rename_file()
end, { buffer = true, desc = 'Rename File' })
